[package]
name = "event-export-sidecar"
version = "0.1.0"
edition = "2021"

[dependencies]
# === Async + Runtime Dependencies === #
tokio = { workspace = true, features = ["full"] }

# === AWS Dependencies === #
aws-config = { version = "1.1.4", features = ["behavior-version-latest"] }
aws-sdk-sqs = "1.50.0"

# === Networking Dependencies === #
reqwest = { version = "0.11" }

# === Workspace Dependencies === #
common = { path = "../../common" }
config = { path = "../../config" }
external-api = { path = "../../external-api", features = ["auth"] }
event-manager = { path = "../../workers/event-manager" }

# === Misc Dependencies === #
url = "2.4"
clap = { version = "4", features = ["derive"] }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
eyre = { workspace = true }
