[package]
name = "event-export-sidecar"
version = "0.1.0"
edition = "2021"

[dependencies]
# === Async + Runtime === #
tokio = { workspace = true, features = ["full"] }

# === Networking Dependencies === #
reqwest = { version = "0.11", features = ["json"] }

# === Workspace Dependencies === #
common = { path = "../../common" }
config = { path = "../../config" }
external-api = { path = "../../external-api", features = ["auth"] }
job-types = { path = "../../workers/job-types" }
event-manager = { path = "../../workers/event-manager" }

# === Misc Dependencies === #
url = "2.4"
clap = { version = "4", features = ["derive"] }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
eyre = { workspace = true }
