[package]
name = "arbitrum-client"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = "2"
renegade_contracts_common = { git = "https://github.com/renegade-fi/renegade-contracts.git", package = "common" }

# === Workspace Dependencies === #
constants = { path = "../constants" }
circuit-types = { path = "../circuit-types" }

# === Serde === #
serde = { workspace = true }
postcard = { version = "1", features = ["alloc"] }
