[package]
name = "arbitrum-client"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = "2"
ark-bn254 = "0.4.0"
ark-ec = "0.4.0"
ark-ff = "0.4.0"
alloy-primitives = "0.3.1"

# === Workspace Dependencies === #
constants = { path = "../constants" }
circuit-types = { path = "../circuit-types" }

# === Serde === #
serde = { workspace = true }
serde_with = "3.4"
postcard = { version = "1", features = ["alloc"] }
