[package]
name = "arbitrum-client"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = "2"
ark-bn254 = "0.4.0"
ark-ec = "0.4.0"
ark-ff = "0.4.0"
alloy-primitives = "0.3.1"
alloy-sol-types = "0.3.1"
num-bigint = { workspace = true }
num-traits = "0.2"
lazy_static = "1.4.0"

# === Workspace Dependencies === #
constants = { path = "../constants" }
circuit-types = { path = "../circuit-types" }
common = { path = "../common" }
renegade-crypto = { path = "../renegade-crypto" }

# === Serde === #
serde = { workspace = true }
serde_with = "3.4"
postcard = { version = "1", features = ["alloc"] }
