match_block_trailing_comma = true
max_width = 100
normalize_comments = true
reorder_imports = true
use_small_heuristics = "Max"
use_try_shorthand = true
use_field_init_shorthand = true
wrap_comments = true
