p2p-port = 8001 
http-port = 3001
websocket-port = 4001
version = 0
debug = true
wallet-file = "./core/resources/wallets2.json"

# A base64 encoded dummy keypair
cluster-public-key = "Ny3zHyKDIpoVwFtAZda9aiavMECEdreTQmO1UDN6RZ8="
cluster-private-key = "BpLAiCutcO0svpbcM252KwoCMaMW41HD/VLSchyFkkg="