p2p-port = 8001
http-port = 3001
websocket-port = 4001
version = 0

# A base64 encoded dummy keypair
cluster-public-key = "ksPP4AJGbB1bUj5acbZ8Ngzy7mCSM3xvE9FDwb5zH0c="
cluster-private-key = "knbytV3abagdJsXKqkL5dkXWaMxho3f8O+85LMr/P+s="