[package]
name = "event-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
# === Async + Concurrency === #
async-trait = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }

# === Workspace Dependencies === #
common = { workspace = true }
constants = { workspace = true }
circuit-types = { workspace = true }
job-types = { workspace = true }
util = { workspace = true, features = ["channels"] }
renegade-metrics = { workspace = true }

# === Misc Dependencies === #
url = "2.4"
tracing = { workspace = true }
metrics = { workspace = true }
serde_json = { workspace = true }
thiserror = { version = "1.0.61" }
tokio-util = "0.7"
