[package]
name = "event-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
# === Async + Concurrency === #
async-trait = { workspace = true }
tokio = { workspace = true }

# === Networking === #
libp2p = { workspace = true }

# === Workspace Dependencies === #
common = { path = "../../common" }
circuit-types = { path = "../../circuit-types" }
job-types = { path = "../job-types" }
