[package]
name = "state-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
# === Proto Dependencies === #
bytes = "1.5"
derive_builder = "0.12"
prost = "0.12"

# === Workspace Dependencies === #
circuit-types = { path = "../../circuit-types" }
common = { path = "../../common" }

# === Misc Dependencies === #
eyre = { workspace = true }
indexmap = "1.9"
itertools = "0.11"
multiaddr = "0.17"
mpc-stark = "0.2"
num-bigint = "0.4"
serde_json = "1.0"
uuid = "1.1.2"

[build-dependencies]
prost-build = "0.12"
