[package]
name = "state-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
# === Proto Dependencies === #
bytes = "1.5"
derive_builder = "0.12"
prost = "0.12"

# === Workspace Dependencies === #
circuit-types = { path = "../../circuit-types" }
common = { path = "../../common" }
util = { path = "../../util" }
constants = { path = "../../constants" }

# === Misc Dependencies === #
eyre = { workspace = true }
indexmap = { workspace = true }
itertools = "0.11"
multiaddr = "0.17"
num-bigint = "0.4"
serde = { workspace = true }
serde_json = "1.0"
uuid = "1.1.2"

[build-dependencies]
prost-build = "0.12"
