services:
  contracts:
    build:
      context: ../contracts
    image: renegade-contracts:latest
    entrypoint: sleep infinity
  sequencer:
    build:
      context: ../devnet
    volumes:
      - deployments:/deployments
    ports:
      - "5050:5050"
    healthcheck:
      test: "curl -X POST -H 'Content-Type: application/json' -d '{\"jsonrpc\":\"2.0\",\"method\":\"starknet_chainId\",\"params\":[],\"id\":1}' http://localhost:5050/rpc || exit 1"
      interval: 5s
      timeout: 10s
      retries: 3
    depends_on:
      - contracts
  relayer:
    build:
      context: ../..
      dockerfile: ./docker/frontend-test-stack/Dockerfile
    ports:
      - "3000:3000"
      - "4000:4000"
      - "8000:8000"
    volumes:
      - deployments:/deployments
    depends_on:
      sequencer:
        condition: service_healthy
volumes:
  deployments:
