//! Job types for the event manager, representing system events to be received &
//! exported by the event manager worker

use std::time::SystemTime;

use serde::{Deserialize, Serialize};
use types_core::{AccountId, Chain};
use util::channels::{TracedTokioReceiver, TracedTokioSender, new_traced_tokio_channel};
use uuid::Uuid;

mod event_types;

pub use event_types::{
    AccountCreationEvent, DepositEvent, ExternalFillEvent, FillEvent, IntentCancellationEvent,
    IntentPlacementEvent, IntentUpdateEvent, TaskCompletionEvent, WithdrawalEvent,
};

// ---------------
// | Queue Types |
// ---------------

/// The queue sender type to send events to the event manager
pub type EventManagerQueue = TracedTokioSender<RelayerEventType>;
/// The queue receiver type to receive events in the event manager
pub type EventManagerReceiver = TracedTokioReceiver<RelayerEventType>;

/// Create a new event manager queue and receiver
pub fn new_event_manager_queue() -> (EventManagerQueue, EventManagerReceiver) {
    new_traced_tokio_channel()
}

// ------------------------
// | Top-level Event Type |
// ------------------------

/// A system event generated by the relayer
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RelayerEvent {
    /// The metadata for the event
    pub meta: RelayerEventMetadata,
    /// The type of event
    pub event_type: RelayerEventType,
}

impl RelayerEvent {
    /// Create a new relayer event
    pub fn new(chain: Chain, event_type: RelayerEventType) -> Self {
        let meta = RelayerEventMetadata::new(chain);
        Self { meta, event_type }
    }

    /// Returns the ID of the wallet for which the event occurred
    pub fn account_id(&self) -> AccountId {
        self.event_type.account_id()
    }

    /// Returns a human-readable description of the event
    pub fn describe(&self) -> String {
        format!("{} ({})", self.event_type.describe(), self.meta.event_id)
    }
}

/// Metadata for a relayer event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RelayerEventMetadata {
    /// The event ID
    pub event_id: Uuid,
    /// The time at which the event occurred
    pub event_timestamp: SystemTime,
    /// The chain on which the event occurred
    pub chain: Chain,
}

impl RelayerEventMetadata {
    /// Creates a new relayer event metadata
    pub fn new(chain: Chain) -> Self {
        let event_id = Uuid::new_v4();
        let event_timestamp = SystemTime::now();
        Self { event_id, event_timestamp, chain }
    }
}

/// An enum capturing all the different types of system events generated by the
/// relayer
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum RelayerEventType {
    /// A account creation event
    AccountCreation(AccountCreationEvent),
    /// A deposit event
    Deposit(DepositEvent),
    /// A withdrawal event
    Withdrawal(WithdrawalEvent),
    /// An intent placement event
    IntentPlacement(IntentPlacementEvent),
    /// An intent update event
    IntentUpdate(IntentUpdateEvent),
    /// An intent cancellation event
    IntentCancellation(IntentCancellationEvent),
    /// A fill event
    Fill(FillEvent),
    /// An external fill event
    ExternalFill(ExternalFillEvent),
    /// A task completion
    TaskCompletion(TaskCompletionEvent),
}

impl RelayerEventType {
    /// Returns the ID of the wallet for which the event occurred
    pub fn account_id(&self) -> AccountId {
        match self {
            RelayerEventType::AccountCreation(event) => event.account_id,
            RelayerEventType::Deposit(event) => event.account_id,
            RelayerEventType::Withdrawal(event) => event.account_id,
            RelayerEventType::IntentPlacement(event) => event.account_id,
            RelayerEventType::IntentUpdate(event) => event.account_id,
            RelayerEventType::IntentCancellation(event) => event.account_id,
            RelayerEventType::Fill(event) => event.account_id,
            RelayerEventType::ExternalFill(event) => event.internal_account_id,
            RelayerEventType::TaskCompletion(event) => event.task_queue_key,
        }
    }

    /// Returns a human-readable description of the event
    pub fn describe(&self) -> String {
        match self {
            RelayerEventType::AccountCreation(event) => event.describe(),
            RelayerEventType::Deposit(event) => event.describe(),
            RelayerEventType::Withdrawal(event) => event.describe(),
            RelayerEventType::IntentPlacement(event) => event.describe(),
            RelayerEventType::IntentUpdate(event) => event.describe(),
            RelayerEventType::IntentCancellation(event) => event.describe(),
            RelayerEventType::Fill(event) => event.describe(),
            RelayerEventType::ExternalFill(event) => event.describe(),
            RelayerEventType::TaskCompletion(event) => event.describe(),
        }
    }
}
