[package]
name = "price-reporter"
version = "0.1.0"
edition = "2024"

[features]
mocks = []

[dependencies]
# === Cryptography === #
jsonwebtoken = "9.3"

# === Async + Runtime === #
async-trait = { workspace = true }
futures = { workspace = true }
futures-util = "0.3"
tokio = { workspace = true }

# === Networking === #
tokio-stream = "0.1"
tokio-tungstenite = { version = "0.18", features = ["native-tls"] }
tungstenite = "0.18"
reqwest = { workspace = true }

# === Workspace Dependencies === #
common = { workspace = true }
constants = { workspace = true }
external-api = { workspace = true }
job-types = { workspace = true }
price-state = { workspace = true }
system-bus = { workspace = true }
util = { workspace = true }

# === Misc Dependencies === #
atomic_float = "0.1"
hex = "0.3.1"
itertools = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
url = "2.4"
