services:
  sequencer:
    build:
      dockerfile: ../docker/devnet/Dockerfile
    ports:
      - "5050:5050"
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:5050/is_alive || exit 1"
      interval: 5s
      timeout: 10s
      retries: 3
  relayer:
    image: task-driver-integration-test:latest
    build: .
    ports:
      - "8000:8000"
    command: >
      cargo test --test integration -- 
        --darkpool-addr 0x02179f01358c09410f234f1ece40d235719e05db3babca7bef0babc974333162 
        --verbose 
    tty: true
    depends_on:
      sequencer:
        condition: service_healthy
