[package]
name = "network-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
# === Concurrency + Networking === #
async-trait = { workspace = true }
futures = { workspace = true }
libp2p = { workspace = true, features = [
    "gossipsub",
    "identify",
    "kad",
    "tokio",
    "quic",
] }
libp2p-core = { workspace = true }
libp2p-swarm = { workspace = true }
libp2p-swarm-derive = { workspace = true }
tokio = { workspace = true }

# === Cryptography === #
ark-mpc = { workspace = true }
ed25519-dalek = { version = "1.0.1", features = ["serde"] }

# === Workspace Dependencies === #
common = { workspace = true }
external-api = { workspace = true }
gossip-api = { workspace = true }
job-types = { workspace = true }
state = { workspace = true }
system-bus = { workspace = true }
util = { workspace = true }

# === Misc Dependencies === #
itertools = "0.11"
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
uuid = "1.1.2"
