[package]
name = "snapshot-sidecar"
description = "Sidecar process that manages snapshots emitted by the relayer"
version = "0.1.0"
edition = "2024"

[dependencies]
# === AWS Deps === #
aws-config = { version = "1.1.4", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1.14.0"

# === Async + Runtime === #
tokio = { workspace = true, features = ["full"] }

# === Workspace Dependencies === #
config = { workspace = true }
external-api = { workspace = true }
util = { workspace = true }

# === Misc Deps === #
clap = { version = "3.1.1", features = ["derive"] }
notify = "6.1"
tracing = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
