//! Helpers for managing tasks generated by the handshake manager

use common::types::tasks::TaskDescriptor;
use job_types::task_driver::TaskDriverJob;
use util::err_str;

use crate::error::HandshakeManagerError;

use super::HandshakeExecutor;

impl HandshakeExecutor {
    /// Enqueue a serial task and await its completion
    pub async fn enqueue_serial_task_await_completion(
        &self,
        descriptor: TaskDescriptor,
    ) -> Result<(), HandshakeManagerError> {
        self.enqueue_task_await_completion(descriptor, true /* is_serial */).await
    }

    /// Enqueue a concurrent task and await its completion
    pub async fn enqueue_concurrent_task_await_completion(
        &self,
        descriptor: TaskDescriptor,
    ) -> Result<(), HandshakeManagerError> {
        self.enqueue_task_await_completion(descriptor, false /* is_serial */).await
    }

    /// Enqueue a task and await its completion
    pub async fn enqueue_task_await_completion(
        &self,
        descriptor: TaskDescriptor,
        is_serial: bool,
    ) -> Result<(), HandshakeManagerError> {
        // Send the proposal to the raft
        let wallets = descriptor.affected_wallets();
        let (tid, waiter) =
            self.state.enqueue_preemptive_task(wallets, descriptor, is_serial).await?;
        waiter.await?;

        // Await a completion notification from the task driver
        let (job, rx) = TaskDriverJob::new_notification(tid);
        self.task_queue.send(job).map_err(err_str!(HandshakeManagerError::SendMessage))?;
        rx.await
            .map_err(err_str!(HandshakeManagerError::TaskError))? // RecvError
            .map_err(err_str!(HandshakeManagerError::TaskError)) // TaskDriverError
    }
}
