[package]
name = "test-helpers"
version = "0.1.0"
edition = "2021"
description = "Helpers for setting up and running integration tests for the relayer"

[dependencies]
# === Runtime + Networking === #
async-trait = "0.1"
dns-lookup = "1.0"
futures = "0.3"
tokio = { workspace = true }
tokio-condvar = "0.1"

# === Cryptography + Arithmetic === #
mpc-stark = { workspace = true }
num-bigint = { version = "0.4", features = ["rand"] }

# === Misc Dependencies === #
inventory = "0.3"
itertools = "0.10.5"
rand = { workspace = true }
serde_json = { workspace = true }
