[package]
name = "api-server"
version = "0.1.0"
edition = "2021"

[dependencies]
# === Cryptography + Arithmetic === #
hmac = "0.12"
k256 = "0.13"
num-bigint = { workspace = true }
num-traits = "0.2"
sha2 = { version = "0.10", features = ["asm"] }

# === HTTP + Websocket === #
hyper = { version = "0.14", features = ["http1", "http2", "server", "tcp"] }
matchit = "0.7"
ratelimit_meter = "5.0.0"
reqwest = { version = "0.12", features = ["json"] }
tokio-stream = "0.1"
tokio-tungstenite = { version = "0.18", features = ["native-tls"] }
tungstenite = "0.18"

# === Runtime + Concurrency === #
crossbeam = { workspace = true }
futures = { workspace = true }
futures-util = "0.3"
tokio = { workspace = true }

# === Ethereum === #
alloy = { workspace = true }

# === Renegade Dependencies === #
darkpool-client = { workspace = true }
circuit-types = { workspace = true }
renegade-compliance-api = { git = "https://github.com/renegade-fi/relayer-extensions", package = "compliance-api" }
config = { workspace = true }
common = { workspace = true }
constants = { workspace = true }
renegade-crypto = { workspace = true }
external-api = { workspace = true, features = ["auth"] }
gossip-api = { workspace = true }
job-types = { workspace = true }
state = { workspace = true }
system-bus = { workspace = true }
task-driver = { workspace = true }
util = { workspace = true }

# === Misc Dependencies === #
async-trait = { workspace = true }
base64 = "0.21"
itertools = "0.11"
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
uuid = "1.1.2"

[dev-dependencies]
ecdsa = "0.16"
rand = { workspace = true }
util = { workspace = true }
