[package]
name = "api-server"
version = "0.1.0"
edition = "2024"

[[test]]
name = "integration"
path = "integration/main.rs"
harness = false
required-features = ["test_helpers"]

[[bench]]
name = "quote_endpoint"
harness = false
required_features = ["test_helpers"]

[[bench]]
name = "book_depth"
harness = false
required_features = ["test_helpers"]

[features]
test_helpers = ["darkpool-client/arbitrum"]

[dependencies]
# === Cryptography + Arithmetic === #
hmac = "0.12"
k256 = "0.13"
num-bigint = { workspace = true }
num-traits = "0.2"
sha2 = { version = "0.10", features = ["asm"] }

# === HTTP + Websocket === #
hyper = { version = "1.6.0", features = ["http1", "http2", "server"] }
hyper-util = "0.1"
http-body-util = "0.1"
matchit = "0.7"
ratelimit_meter = "5.0.0"
reqwest = { workspace = true, features = ["json"] }
tokio-stream = "0.1"
tokio-tungstenite = { version = "0.18", features = ["native-tls"] }
tungstenite = "0.18"

# === Runtime + Concurrency === #
crossbeam = { workspace = true }
futures = { workspace = true }
futures-util = "0.3"
tokio = { workspace = true }

# === Ethereum === #
alloy = { workspace = true }

# === Renegade Dependencies === #
darkpool-client = { workspace = true }
circuit-types = { workspace = true }
renegade-compliance-api = { git = "https://github.com/renegade-fi/relayer-extensions", package = "compliance-api" }
config = { workspace = true }
common = { workspace = true }
constants = { workspace = true }
renegade-crypto = { workspace = true }
external-api = { workspace = true, features = ["auth"] }
gossip-api = { workspace = true }
job-types = { workspace = true }
price-state = { workspace = true }
state = { workspace = true }
system-bus = { workspace = true }
task-driver = { workspace = true }
util = { workspace = true }

# === Misc Dependencies === #
async-trait = { workspace = true }
base64 = "0.21"
itertools = "0.11"
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
uuid = "1.1.2"

[dev-dependencies]
ecdsa = "0.16"
rand = { workspace = true }
util = { workspace = true }

# === Bench Utils === #
api-server-bench-util = { path = "benches/api-server-bench-util" }

# === Integration Test Dependencies === #
clap = { version = "4.0", features = ["derive"] }
colored = "2"
criterion = { version = "0.5", features = ["async", "async_tokio"] }
ctor = "0.1"
eyre = { workspace = true }
inventory = "0.3"
test-helpers = { workspace = true, features = ["mpc-network", "test-harness"] }
tokio = { version = "1.12", features = ["macros", "rt-multi-thread"] }
mock-node = { workspace = true }
