[package]
name = "handshake-manager-tests"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "handshake-manager-tests"
path = "src/main.rs"

[dependencies]
# === Test Harness === #
clap = { version = "4.0", features = ["derive"] }
colored = "2"
eyre = { workspace = true }
inventory = "0.3"

# === Runtime + Networking === #
libp2p = { workspace = true }
tokio = { workspace = true }

# === Ethereum === #
alloy = { workspace = true }

# === Workspace Dependencies === #
arbitrum-client = { workspace = true }
circuit-types = { workspace = true }
common = { workspace = true }
config = { workspace = true }
constants = { workspace = true }
job-types = { workspace = true }
mock-node = { workspace = true }
test-helpers = { workspace = true, features = ["arbitrum"] }
util = { workspace = true }

# === Misc Dependencies === #
ark-mpc = { workspace = true }
base64 = "0.13"
lazy_static = { workspace = true }
tracing = { workspace = true }
num-bigint = "0.4"
rand = { workspace = true }
uuid = { version = "1.1.2", features = ["v4"] }
