[package]
name = "handshake-manager-tests"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "handshake-manager-tests"
path = "src/main.rs"

[dependencies]
# === Test Harness === #
clap = { version = "4.0", features = ["derive"] }
colored = "2"
eyre = { workspace = true }
inventory = "0.3"

# === Runtime + Networking === #
libp2p = { workspace = true }
tokio = { workspace = true }

# === Workspace Dependencies === #
arbitrum-client = { path = "../../arbitrum-client" }
config = { path = "../../config" }
job-types = { path = "../job-types" }
mock-node = { path = "../../mock-node" }
test-helpers = { path = "../../test-helpers" }
util = { path = "../../util" }

# === Misc Dependencies === #
base64 = "0.13"
lazy_static = "1.4"
tracing = { workspace = true }
