[package]
name = "external-api"
version = "0.1.0"
edition = "2021"

[dependencies]
# === Arithmetic === #
num-bigint = { workspace = true }

# === Workspace Dependencies === #
circuit-types = { path = "../circuit-types" }
common = { path = "../common" }
constants = { path = "../constants" }
renegade-crypto = { path = "../renegade-crypto" }
util = { path = "../util" }

# === Misc Dependencies === #
itertools = { workspace = true }
hex = "0.4"
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { version = "1.1.2", features = ["v4", "serde"] }
