[package]
name = "external-api"
version = "0.1.0"
edition = "2021"

[dependencies]
# === Arithmetic === #
num-bigint = { workspace = true }
num-traits = "0.2"

# === Workspace Dependencies === #
circuit-types = { path = "../circuit-types" } 
common = { path = "../common" }
crypto = { path = "../crypto" }

# === Misc Dependencies === #
itertools = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { version = "1.1.2", features = ["v4", "serde"] }