[package]
name = "common"
version = "0.1.0"
edition = "2021"

[features]
mocks = ["rand"]

[dependencies]
# === Cryptography + Arithmetic === #
ed25519-dalek = { version = "1.0.1", features = ["serde"] }
mpc-bulletproof = { workspace = true }
mpc-stark = { workspace = true }
num-bigint = { workspace = true }

# === Runtime + Networking === #
crossbeam = { workspace = true }
libp2p = { workspace = true }
libp2p-identity = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

# === Workspace Dependencies === #
circuits = { path = "../circuits" }
circuit-types = { path = "../circuit-types" }
constants = { path = "../constants" }
renegade-crypto = { path = "../renegade-crypto" }
util = { path = "../util" }

# === Misc Dependencies === #
base64 = { version = "0.13" }
bimap = "0.6.2"
derivative = "2.2"
indexmap = "1.9"
itertools = "0.10"
lazy_static = "1.4"
rand = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
starknet = { workspace = true }
uuid = { version = "1.1.2", features = ["v4", "serde"] }

[dev-dependencies]
rand_core = "0.5"
rand = { workspace = true }
