[package]
name = "task-driver"
version = "0.1.0"
edition = "2021"

[features]
integration = [
    "state/mocks",
    "common/mocks",
    "arbitrum-client/integration",
    "util/mocks",
]

[[test]]
name = "integration"
path = "integration/main.rs"
harness = false
required-features = ["integration"]

[dependencies]
# === Async + Runtime === #
async-trait = "0.1.60"
crossbeam = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }

# === Cryptography === #
ark-mpc = { workspace = true }
num-bigint = { workspace = true }

# === Workspace Dependencies === #
arbitrum-client = { path = "../../arbitrum-client" }
circuits = { path = "../../circuits" }
circuit-types = { path = "../../circuit-types" }
common = { path = "../../common" }
constants = { path = "../../constants" }
external-api = { path = "../../external-api" }
gossip-api = { path = "../../gossip-api" }
job-types = { path = "../job-types" }
renegade-crypto = { path = "../../renegade-crypto" }
state = { path = "../../state" }
system-bus = { path = "../../system-bus" }
util = { path = "../../util" }
renegade-metrics = { path = "../../renegade-metrics" }

# === Misc Dependencies === #
itertools = "0.11"
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
uuid = { version = "1.1.2", features = ["v4", "serde"] }
metrics = { workspace = true }

[dev-dependencies]
ethers = { workspace = true }
alloy-primitives = "0.3.1"

clap = { version = "4.0", features = ["derive"] }
colored = "2"
eyre = { workspace = true }
inventory = "0.3"

lazy_static = { workspace = true }
num-traits = "0.2"

rand = { workspace = true }
test-helpers = { path = "../../test-helpers" }
util = { path = "../../util" }

proof-manager = { path = "../proof-manager", features = ["mocks"] }
