[package]
name = "task-driver"
version = "0.1.0"
edition = "2021"

[features]
integration = [
    "state/mocks",
    "common/mocks",
    "arbitrum-client/integration",
    "util/mocks",
]

[[test]]
name = "integration"
path = "integration/main.rs"
harness = false
required-features = ["integration"]

[dependencies]
# === Async + Runtime === #
async-trait = { workspace = true }
crossbeam = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }

# === Cryptography === #
ark-mpc = { workspace = true }
num-bigint = { workspace = true }

# === Workspace Dependencies === #
arbitrum-client = { workspace = true }
circuits = { workspace = true }
circuit-types = { workspace = true }
common = { workspace = true }
constants = { workspace = true }
external-api = { workspace = true }
gossip-api = { workspace = true }
job-types = { workspace = true }
renegade-crypto = { workspace = true }
state = { workspace = true }
system-bus = { workspace = true }
util = { workspace = true }
renegade-metrics = { workspace = true }

# === Misc Dependencies === #
ethers = { workspace = true }
itertools = "0.11"
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
uuid = { version = "1.1.2", features = ["v4", "serde"] }
metrics = { workspace = true }

[dev-dependencies]
ethers = { workspace = true }
alloy-primitives = { workspace = true }

clap = { version = "4.0", features = ["derive"] }
colored = "2"
eyre = { workspace = true }
inventory = "0.3"

lazy_static = { workspace = true }
num-traits = "0.2"

rand = { workspace = true }
test-helpers = { workspace = true, features = ["arbitrum"] }
util = { workspace = true, features = [
    "blockchain",
    "concurrency",
    "telemetry",
] }

proof-manager = { workspace = true, features = ["mocks"] }
