[package]
name = "handshake-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
# === Arithmetic and Cryptography === #
ark-mpc = { workspace = true }
mpc-plonk = { workspace = true }

# === Concurrency + Networking === #
async-trait = { workspace = true }
crossbeam = { workspace = true }
futures = { workspace = true }
libp2p = { workspace = true }
tokio = { workspace = true }

#=== Workspace Dependencies === #
arbitrum-client = { workspace = true }
circuits = { workspace = true }
circuit-types = { workspace = true }
common = { workspace = true }
constants = { workspace = true }
renegade-crypto = { workspace = true }
external-api = { workspace = true }
job-types = { workspace = true }
gossip-api = { workspace = true }
state = { workspace = true }
system-bus = { workspace = true }
test-helpers = { workspace = true, features = [
    "mpc-network",
], default-features = false }
util = { workspace = true, features = ["matching-engine"] }
renegade-metrics = { workspace = true }

# === Misc Dependencies === #
ark-serialize = "0.4"
itertools = "0.11"
lazy_static = { workspace = true }
lru = "0.11"
portpicker = "0.1"
rand = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
uuid = { version = "1.1.2", features = ["v4", "serde"] }

[dev-dependencies]
clap = { version = "4.0", features = ["derive"] }
colored = "2"
eyre = { workspace = true }
inventory = "0.3"

lazy_static = { workspace = true }
num-traits = "0.2"

rand = { workspace = true }
util = { workspace = true }
proof-manager = { workspace = true, features = ["mocks"] }
