[package]
name = "handshake-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
# === Arithmetic and Cryptography === #
ark-mpc = { workspace = true }
mpc-plonk = { workspace = true }

# === Concurrency + Networking === #
async-trait = { workspace = true }
crossbeam = { workspace = true }
futures = { workspace = true }
libp2p = { workspace = true }
tokio = { workspace = true }

#=== Workspace Dependencies === #
arbitrum-client = { path = "../../arbitrum-client" }
circuits = { path = "../../circuits" }
circuit-types = { path = "../../circuit-types" }
common = { path = "../../common" }
constants = { path = "../../constants" }
renegade-crypto = { path = "../../renegade-crypto" }
external-api = { path = "../../external-api" }
job-types = { path = "../job-types" }
gossip-api = { path = "../../gossip-api" }
state = { path = "../../state" }
system-bus = { path = "../../system-bus" }
test-helpers = { path = "../../test-helpers", features = [
    "mpc-network",
], default-features = false }
util = { path = "../../util", features = ["matching-engine"] }
renegade-metrics = { path = "../../renegade-metrics" }

# === Misc Dependencies === #
ark-serialize = "0.4"
itertools = "0.11"
lazy_static = { workspace = true }
lru = "0.11"
portpicker = "0.1"
rand = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
uuid = { version = "1.1.2", features = ["v4", "serde"] }

[dev-dependencies]
clap = { version = "4.0", features = ["derive"] }
colored = "2"
eyre = { workspace = true }
inventory = "0.3"

lazy_static = { workspace = true }
num-traits = "0.2"

rand = { workspace = true }
util = { path = "../../util" }

proof-manager = { path = "../proof-manager", features = ["mocks"] }
