services:
  sequencer:
    image: sequencer
    ports:
      - "8547:8547"
    build:
      context: ../../docker/sequencer
      args:
        - NO_VERIFY=1
    attach: false
    healthcheck:
      test: curl -sf http://localhost:8547
      interval: 1s
      timeout: 5s
      retries: 10

  peer1:
    image: handshake-manager-integration-test:latest
    build:
      context: ../..
      dockerfile: workers/handshake-manager/Dockerfile
    ports:
      - "8000:8000"
    command: >
      cargo run -- 
        --peer-index 0
        --my-key CAESQILfhGLsZ1CgLHRO5iozioKNXORP8+htmHzVm/PE77OHfqOQXKJivIdJrbwNMnXGZvS6yuzMDdaLb9dE692OPls=
        --my-port 8000
        --peer-key CAESQFEmvYSO+0/w0ZTTxQIvEudx7lwPZop8nbQvbkb+66ZQPU5BRHlgJuBSdljUBY4Eb/JAuPL3BM0sL3q8J6JCbek=
        --peer-port 8001
        --deployments-path /deployments.json
        --devnet-url http://sequencer:8547
    tty: true
    depends_on:
      sequencer:
        condition: service_healthy

  peer2:
    image: handshake-manager-integration-test:latest
    build:
      context: ../..
      dockerfile: workers/handshake-manager/Dockerfile
    ports:
      - "8001:8001"
    command: >
      cargo run --
        --peer-index 1
        --my-key CAESQFEmvYSO+0/w0ZTTxQIvEudx7lwPZop8nbQvbkb+66ZQPU5BRHlgJuBSdljUBY4Eb/JAuPL3BM0sL3q8J6JCbek=
        --my-port 8001
        --peer-key CAESQILfhGLsZ1CgLHRO5iozioKNXORP8+htmHzVm/PE77OHfqOQXKJivIdJrbwNMnXGZvS6yuzMDdaLb9dE692OPls=
        --peer-port 8000
        --deployments-path /deployments.json
        --devnet-url http://sequencer:8547
        --verbosity full
    tty: true
    depends_on:
      sequencer:
        condition: service_healthy
