services:
  party0:
    image: circuits-integration-test:latest
    build:
      context: ..
      dockerfile: circuits/Dockerfile
    ports:
      - "8000:8000"
    command: >
      cargo test --test integration --
        --party 0 
        --port1 8000 
        --port2 9000 
        --docker 
        --verbose
    tty: true
  party1:
    image: circuits-integration-test:latest
    build:
      context: ..
      dockerfile: circuits/Dockerfile
    ports:
      - "9000:9000"
    command: >
      cargo test --test integration -- 
        --party 1 
        --port1 9000 
        --port2 8000 
        --docker
    tty: true
