[package]
name = "chain-events"
version = "0.1.0"
edition = "2021"

[dependencies]
# === Concurrency + Runtime === #
crossbeam = { workspace = true }
tokio = { workspace = true }

# === Crypto === #
ethers = { workspace = true }

# === Workspace Dependencies === #
arbitrum-client = { path = "../../arbitrum-client" }
circuit-types = { path = "../../circuit-types" }
common = { path = "../../common" }
constants = { path = "../../constants" }
renegade-crypto = { path = "../../renegade-crypto" }
gossip-api = { path = "../../gossip-api" }
job-types = { path = "../job-types" }
state = { path = "../../state" }
util = { path = "../../util" }

# === Misc Dependencies === #
lazy_static = { workspace = true }
async-trait = { workspace = true }
rand = { workspace = true }
tracing = { workspace = true }
