[package]
name = "chain-events"
version = "0.1.0"
edition = "2021"

[dependencies]
# === Concurrency + Runtime === #
crossbeam = { workspace = true }
tokio = { workspace = true }

# === Crypto === #
ethers = "2"

# === Workspace Dependencies === #
arbitrum-client = { path = "../../arbitrum-client" }
circuit-types = { path = "../../circuit-types" }
common = { path = "../../common" }
renegade-crypto = { path = "../../renegade-crypto" }
gossip-api = { path = "../../gossip-api" }
job-types = { path = "../job-types" }
statev2 = { path = "../../statev2" }
task-driver = { path = "../../task-driver" }

# === Misc Dependencies === #
lazy_static = "1.4"
tracing = { workspace = true }
