[package]
name = "chain-events"
version = "0.1.0"
edition = "2021"

[dependencies]
# === Concurrency + Runtime === #
crossbeam = { workspace = true }
tokio = { workspace = true }

# === Crypto === #
alloy = { workspace = true, features = ["provider-ws"] }

# === Workspace Dependencies === #
arbitrum-client = { workspace = true }
circuit-types = { workspace = true }
common = { workspace = true }
constants = { workspace = true }
renegade-crypto = { workspace = true }
renegade-metrics = { workspace = true }
gossip-api = { workspace = true }
job-types = { workspace = true }
state = { workspace = true }
util = { workspace = true }

# === Misc Dependencies === #
async-trait = { workspace = true }
futures-util = "0.3.31"
lazy_static = { workspace = true }
rand = { workspace = true }
tracing = { workspace = true }
