[package]
name = "gossip-server"
version = "0.1.0"
edition = "2021"

[dependencies]
# === Async + Concurrency === #
async-trait = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }

# === Networking === #
libp2p = { workspace = true }

# === Workspace Dependencies === #
arbitrum-client = { path = "../../arbitrum-client" }
circuits = { path = "../../circuits" }
circuit-types = { path = "../../circuit-types" }
common = { path = "../../common" }
constants = { path = "../../constants" }
gossip-api = { path = "../../gossip-api" }
job-types = { path = "../job-types" }
state = { path = "../../state" }
util = { path = "../../util" }
renegade-metrics = { path = "../../renegade-metrics" }

# === Misc Dependencies === #
itertools = { workspace = true }
lru = "0.11"
tracing = "0.1"
metrics = { workspace = true }
