[package]
name = "gossip-server"
version = "0.1.0"
edition = "2021"

[dependencies]
# === Async + Concurrency === #
async-trait = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }

# === Networking === #
libp2p = { workspace = true }

# === Workspace Dependencies === #
arbitrum-client = { workspace = true }
circuits = { workspace = true }
circuit-types = { workspace = true }
common = { workspace = true }
constants = { workspace = true }
gossip-api = { workspace = true }
job-types = { workspace = true }
state = { workspace = true }
util = { workspace = true }
renegade-metrics = { workspace = true }

# === Misc Dependencies === #
itertools = { workspace = true }
lru = "0.11"
tracing = "0.1"
metrics = { workspace = true }
