[package]
name = "gossip-server"
version = "0.1.0"
edition = "2021"

[dependencies]
# === Async + Concurrency === #
futures = { version = "0.3.26" }
tokio = { workspace = true }

# === Networking === #
libp2p = { workspace = true }

# === Workspace Dependencies === #
circuits = { path = "../../circuits" }
circuit-types = { path = "../../circuit-types" }
common = { path = "../../common" }
gossip-api = { path = "../../gossip-api" }
job-types = { path = "../job-types" }
starknet-client = { path = "../../starknet-client" }
state = { path = "../../state" }
util = { path = "../../util" }

# === Misc Dependencies === #
lru = "0.11"
tracing = "0.1"