[package]
name = "statev2"
version = "0.1.0"
edition = "2021"

[dependencies]

# === Replication === #
raft = "0.7"

# === Storage === #
flexbuffers = "2.0"
libmdbx = "0.3"
protobuf = "2.0"
serde = { workspace = true, features = ["derive"] }

# === Messaging + Concurrency === #
tokio = { workspace = true }

# === Workspace Dependencies === #
common = { path = "../../common" }
constants = { path = "../../constants" }
external-api = { path = "../../external-api" }
job-types = { path = "../../workers/job-types" }
state-proto = { path = "../proto" }
system-bus = { path = "../../system-bus" }

# === Misc === #
itertools = "0.10"
mpc-stark = "0.2"
slog = "2.2"
tracing = { workspace = true, features = ["log"] }
tracing-slog = "0.2"

[dev-dependencies]
crossbeam = "0.8"
multiaddr = "0.17"
tempfile = "3.8"
rand = { workspace = true }
uuid = "1.4"
