//! Job types for the event manager, representing system events to be received &
//! exported by the event manager worker

use std::time::SystemTime;

use circuit_types::{
    r#match::{ExternalMatchResult, FeeTake, MatchResult},
    transfers::ExternalTransfer,
    Amount,
};
use common::types::{
    tasks::{HistoricalTask, TaskQueueKey},
    wallet::{Order, OrderIdentifier, WalletIdentifier},
    MatchingPoolName, TimestampedPrice,
};
use serde::{Deserialize, Serialize};
use tokio::sync::mpsc::{unbounded_channel, UnboundedSender as TokioSender};
use util::metered_channels::MeteredTokioReceiver;
use uuid::Uuid;

// ---------------
// | Queue Types |
// ---------------

/// The name of the event manager queue, used to label queue length metrics
const EVENT_MANAGER_QUEUE_NAME: &str = "event_manager";

/// The queue sender type to send events to the event manager
pub type EventManagerQueue = TokioSender<RelayerEvent>;
/// The queue receiver type to receive events in the event manager
pub type EventManagerReceiver = MeteredTokioReceiver<RelayerEvent>;

/// Create a new event manager queue and receiver
pub fn new_event_manager_queue() -> (EventManagerQueue, EventManagerReceiver) {
    let (send, recv) = unbounded_channel();
    (send, MeteredTokioReceiver::new(recv, EVENT_MANAGER_QUEUE_NAME))
}

// ------------------------
// | Top-level Event Enum |
// ------------------------

/// A system event generated by the relayer
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum RelayerEvent {
    /// A wallet creation event
    WalletCreation(WalletCreationEvent),
    /// An external transfer event
    ExternalTransfer(ExternalTransferEvent),
    /// An order placement event
    OrderPlacement(OrderPlacementEvent),
    /// An order update event
    OrderUpdate(OrderUpdateEvent),
    /// An order cancellation event
    OrderCancellation(OrderCancellationEvent),
    /// A fill event
    Fill(FillEvent),
    /// An external fill event
    ExternalFill(ExternalFillEvent),
    /// A task completion
    TaskCompletion(TaskCompletionEvent),
}

impl RelayerEvent {
    /// Returns the event ID
    pub fn event_id(&self) -> Uuid {
        match self {
            RelayerEvent::WalletCreation(event) => event.event_id,
            RelayerEvent::ExternalTransfer(event) => event.event_id,
            RelayerEvent::OrderPlacement(event) => event.event_id,
            RelayerEvent::OrderUpdate(event) => event.event_id,
            RelayerEvent::OrderCancellation(event) => event.event_id,
            RelayerEvent::Fill(event) => event.event_id,
            RelayerEvent::ExternalFill(event) => event.event_id,
            RelayerEvent::TaskCompletion(event) => event.event_id,
        }
    }

    /// Returns the event timestamp
    pub fn event_timestamp(&self) -> SystemTime {
        match self {
            RelayerEvent::WalletCreation(event) => event.event_timestamp,
            RelayerEvent::ExternalTransfer(event) => event.event_timestamp,
            RelayerEvent::OrderPlacement(event) => event.event_timestamp,
            RelayerEvent::OrderUpdate(event) => event.event_timestamp,
            RelayerEvent::OrderCancellation(event) => event.event_timestamp,
            RelayerEvent::Fill(event) => event.event_timestamp,
            RelayerEvent::ExternalFill(event) => event.event_timestamp,
            RelayerEvent::TaskCompletion(event) => event.event_timestamp,
        }
    }

    /// Returns the ID of the wallet for which the event occurred
    pub fn wallet_id(&self) -> WalletIdentifier {
        match self {
            RelayerEvent::WalletCreation(event) => event.wallet_id,
            RelayerEvent::ExternalTransfer(event) => event.wallet_id,
            RelayerEvent::OrderPlacement(event) => event.wallet_id,
            RelayerEvent::OrderUpdate(event) => event.wallet_id,
            RelayerEvent::OrderCancellation(event) => event.wallet_id,
            RelayerEvent::Fill(event) => event.wallet_id,
            RelayerEvent::ExternalFill(event) => event.internal_wallet_id,
            RelayerEvent::TaskCompletion(event) => event.task_queue_key,
        }
    }

    /// Returns a human-readable description of the event
    pub fn describe(&self) -> String {
        match self {
            RelayerEvent::WalletCreation(event) => event.describe(),
            RelayerEvent::ExternalTransfer(event) => event.describe(),
            RelayerEvent::OrderPlacement(event) => event.describe(),
            RelayerEvent::OrderUpdate(event) => event.describe(),
            RelayerEvent::OrderCancellation(event) => event.describe(),
            RelayerEvent::Fill(event) => event.describe(),
            RelayerEvent::ExternalFill(event) => event.describe(),
            RelayerEvent::TaskCompletion(event) => event.describe(),
        }
    }
}

// --------------------------
// | Individual Event Types |
// --------------------------

/// A wallet creation event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WalletCreationEvent {
    /// The event ID
    pub event_id: Uuid,
    /// The time at which the event occurred
    pub event_timestamp: SystemTime,

    /// The ID of the wallet that was created
    pub wallet_id: WalletIdentifier,
    /// The wallet's symmetric key, base64-encoded
    pub symmetric_key: String,
}

impl WalletCreationEvent {
    /// Creates a new wallet creation event
    pub fn new(wallet_id: WalletIdentifier, symmetric_key: String) -> Self {
        let (event_id, event_timestamp) = get_event_id_and_timestamp();
        Self { event_id, event_timestamp, wallet_id, symmetric_key }
    }

    /// Returns a human-readable description of the event
    pub fn describe(&self) -> String {
        format!("WalletCreation({})", self.event_id)
    }
}

/// An external transfer event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExternalTransferEvent {
    /// The event ID
    pub event_id: Uuid,
    /// The time at which the event occurred
    pub event_timestamp: SystemTime,

    /// The ID of the wallet that made the transfer
    pub wallet_id: WalletIdentifier,
    /// The transfer that occurred
    pub transfer: ExternalTransfer,
}

impl ExternalTransferEvent {
    /// Creates a new external transfer event
    pub fn new(wallet_id: WalletIdentifier, transfer: ExternalTransfer) -> Self {
        let (event_id, event_timestamp) = get_event_id_and_timestamp();
        Self { event_id, event_timestamp, wallet_id, transfer }
    }

    /// Returns a human-readable description of the event
    pub fn describe(&self) -> String {
        format!("ExternalTransfer({})", self.event_id)
    }
}

/// An order placement event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderPlacementEvent {
    /// The event ID
    pub event_id: Uuid,
    /// The time at which the event occurred
    pub event_timestamp: SystemTime,

    /// The ID of the wallet that placed the order
    pub wallet_id: WalletIdentifier,
    /// The ID of the order that was placed
    pub order_id: OrderIdentifier,
    /// The placed order
    pub order: Order,
    /// The matching pool to which the order was assigned
    pub matching_pool: MatchingPoolName,
}

impl OrderPlacementEvent {
    /// Creates a new order placement event
    pub fn new(
        wallet_id: WalletIdentifier,
        order_id: OrderIdentifier,
        order: Order,
        matching_pool: MatchingPoolName,
    ) -> Self {
        let (event_id, event_timestamp) = get_event_id_and_timestamp();
        Self { event_id, event_timestamp, wallet_id, order_id, order, matching_pool }
    }

    /// Returns a human-readable description of the event
    pub fn describe(&self) -> String {
        format!("OrderPlacement({})", self.event_id)
    }
}

/// An order update event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderUpdateEvent {
    /// The event ID
    pub event_id: Uuid,
    /// The time at which the event occurred
    pub event_timestamp: SystemTime,

    /// The ID of the wallet that updated the order
    pub wallet_id: WalletIdentifier,
    /// The ID of the order that was updated
    pub order_id: OrderIdentifier,
    /// The updated order
    pub order: Order,
    /// The matching pool to which the order was assigned
    pub matching_pool: MatchingPoolName,
}

impl OrderUpdateEvent {
    /// Creates a new order update event
    pub fn new(
        wallet_id: WalletIdentifier,
        order_id: OrderIdentifier,
        order: Order,
        matching_pool: MatchingPoolName,
    ) -> Self {
        let (event_id, event_timestamp) = get_event_id_and_timestamp();
        Self { event_id, event_timestamp, wallet_id, order_id, order, matching_pool }
    }

    /// Returns a human-readable description of the event
    pub fn describe(&self) -> String {
        format!("OrderUpdate({})", self.event_id)
    }
}

/// An order cancellation event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderCancellationEvent {
    /// The event ID
    pub event_id: Uuid,
    /// The time at which the event occurred
    pub event_timestamp: SystemTime,

    /// The ID of the wallet that cancelled the order
    pub wallet_id: WalletIdentifier,
    /// The ID of the order that was cancelled
    pub order_id: OrderIdentifier,
    /// The cancelled order
    pub order: Order,
    /// The remaining amount of the base asset in the order
    pub amount_remaining: Amount,
    /// The filled amount of the base asset in the order
    pub amount_filled: Amount,
}

impl OrderCancellationEvent {
    /// Creates a new order cancellation event
    pub fn new(
        wallet_id: WalletIdentifier,
        order_id: OrderIdentifier,
        order: Order,
        amount_remaining: Amount,
        amount_filled: Amount,
    ) -> Self {
        let (event_id, event_timestamp) = get_event_id_and_timestamp();
        Self {
            event_id,
            event_timestamp,
            wallet_id,
            order_id,
            order,
            amount_remaining,
            amount_filled,
        }
    }

    /// Returns a human-readable description of the event
    pub fn describe(&self) -> String {
        format!("OrderCancellation({})", self.event_id)
    }
}

/// A fill event on an order, resulting from an internal match
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FillEvent {
    /// The event ID
    pub event_id: Uuid,
    /// The time at which the event occurred
    pub event_timestamp: SystemTime,

    /// The ID of the wallet containing the filled order
    pub wallet_id: WalletIdentifier,
    /// The ID of the order that received the fill
    pub order_id: OrderIdentifier,
    /// The price at which the fill was executed
    pub execution_price: TimestampedPrice,
    /// The match result
    pub match_result: MatchResult,
    /// The fees paid as a result of the fill
    pub fee_take: FeeTake,
}

impl FillEvent {
    /// Creates a new fill event
    pub fn new(
        wallet_id: WalletIdentifier,
        order_id: OrderIdentifier,
        execution_price: TimestampedPrice,
        match_result: MatchResult,
        fee_take: FeeTake,
    ) -> Self {
        let (event_id, event_timestamp) = get_event_id_and_timestamp();
        Self {
            event_id,
            event_timestamp,
            wallet_id,
            order_id,
            execution_price,
            match_result,
            fee_take,
        }
    }

    /// Returns a human-readable description of the event
    pub fn describe(&self) -> String {
        format!("Fill({})", self.event_id)
    }
}

/// A fill event on an order, resulting from an external match
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExternalFillEvent {
    /// The event ID
    pub event_id: Uuid,
    /// The time at which the event occurred
    pub event_timestamp: SystemTime,

    /// The ID of the internal wallet containing the filled order
    pub internal_wallet_id: WalletIdentifier,
    /// The ID of the internal order that received the fill
    pub internal_order_id: OrderIdentifier,
    /// The price at which the fill was executed
    pub execution_price: TimestampedPrice,
    /// The external match result
    pub external_match_result: ExternalMatchResult,
    /// The fees paid by the internal party as a result of the fill
    pub internal_fee_take: FeeTake,
}

impl ExternalFillEvent {
    /// Creates a new external fill event
    pub fn new(
        internal_wallet_id: WalletIdentifier,
        internal_order_id: OrderIdentifier,
        execution_price: TimestampedPrice,
        external_match_result: ExternalMatchResult,
        internal_fee_take: FeeTake,
    ) -> Self {
        let (event_id, event_timestamp) = get_event_id_and_timestamp();
        Self {
            event_id,
            event_timestamp,
            internal_wallet_id,
            internal_order_id,
            execution_price,
            external_match_result,
            internal_fee_take,
        }
    }

    /// Returns a human-readable description of the event
    pub fn describe(&self) -> String {
        format!("ExternalFill({})", self.event_id)
    }
}

/// A task completion event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskCompletionEvent {
    /// The event ID
    pub event_id: Uuid,
    /// The time at which the event occurred
    pub event_timestamp: SystemTime,

    /// The key of the queue in which the task was executed
    pub task_queue_key: TaskQueueKey,
    /// The historical task that was completed
    pub historical_task: HistoricalTask,
}

impl TaskCompletionEvent {
    /// Creates a new task completion event
    pub fn new(task_queue_key: TaskQueueKey, historical_task: HistoricalTask) -> Self {
        let (event_id, event_timestamp) = get_event_id_and_timestamp();
        Self { event_id, event_timestamp, task_queue_key, historical_task }
    }

    /// Returns a human-readable description of the event
    pub fn describe(&self) -> String {
        format!("TaskCompletion({})", self.event_id)
    }
}

// -----------
// | Helpers |
// -----------

/// Generates a new event ID and timestamp
fn get_event_id_and_timestamp() -> (Uuid, SystemTime) {
    (Uuid::new_v4(), SystemTime::now())
}
