//! Helpers for managing tasks generated by the handshake manager

use job_types::task_driver::TaskDriverJob;
use types_tasks::{QueuedTask, TaskDescriptor};

use crate::{error::MatchingEngineError, executor::MatchingEngineExecutor};

impl MatchingEngineExecutor {
    /// Enqueue a serial task and await its completion
    pub async fn forward_queued_task(
        &self,
        descriptor: TaskDescriptor,
    ) -> Result<(), MatchingEngineError> {
        self.enqueue_task_await_completion(descriptor, false /* bypass_queue */).await
    }

    /// Enqueue a concurrent task and await its completion
    pub async fn forward_bypassing_task(
        &self,
        descriptor: TaskDescriptor,
    ) -> Result<(), MatchingEngineError> {
        self.enqueue_task_await_completion(descriptor, true /* bypass_queue */).await
    }

    /// Enqueue a task and await its completion
    async fn enqueue_task_await_completion(
        &self,
        descriptor: TaskDescriptor,
        bypass_queue: bool,
    ) -> Result<(), MatchingEngineError> {
        if bypass_queue {
            self.send_task_to_driver(descriptor).await
        } else {
            self.enqueue_task_through_raft(descriptor).await
        }
    }

    /// Enqueue a task through the raft task queue abstraction
    async fn enqueue_task_through_raft(
        &self,
        descriptor: TaskDescriptor,
    ) -> Result<(), MatchingEngineError> {
        // Send the proposal to the raft. The serial-preemption reject is
        // surfaced as a typed `PreemptionConflict` (transient, retryable by the
        // caller); all other state errors propagate normally.
        let accounts = descriptor.affected_accounts();
        let (tid, waiter) = match self
            .state
            .enqueue_preemptive_task(accounts, descriptor, true /* is_serial */)
            .await
        {
            Ok(res) => res,
            Err(e) if e.is_serial_preemption_conflict() => {
                return Err(MatchingEngineError::PreemptionConflict);
            },
            Err(e) => return Err(e.into()),
        };

        // The reject is typically surfaced when the proposal is applied (via the
        // waiter), so classify it there too.
        if let Err(e) = waiter.await {
            if e.is_serial_preemption_conflict() {
                return Err(MatchingEngineError::PreemptionConflict);
            }
            return Err(e.into());
        }

        // Await a completion notification from the task driver
        let (job, rx) = TaskDriverJob::new_notification(tid);
        self.task_queue.send(job).map_err(MatchingEngineError::send_message)?;
        rx.await
            .map_err(MatchingEngineError::task)? // RecvError
            .map_err(MatchingEngineError::task) // TaskDriverError
    }

    /// Enqueue a task directly to the task driver
    async fn send_task_to_driver(
        &self,
        descriptor: TaskDescriptor,
    ) -> Result<(), MatchingEngineError> {
        // Send the task to the task driver
        let queued = QueuedTask::new(descriptor);
        let (job, rx) = TaskDriverJob::run_with_notification(queued);
        self.task_queue.send(job).map_err(MatchingEngineError::send_message)?;

        // Await a completion notification from the task driver
        rx.await
            .map_err(MatchingEngineError::task)? // RecvError
            .map_err(MatchingEngineError::task) // TaskDriverError
    }
}
